// 'use server'
import { Inter } from "next/font/google";
import "./globals.css";
import { AlbumProvider } from "./context/AlbumContext";
import ReviewProvider from "./context/ReviewContext";
import { ClerkProvider } from "@clerk/nextjs";
import { ToastContainer } from "react-toastify";
import SubscriberProvider from "./context/SubscriberContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Raj Artist",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className} suppressHydrationWarning={true}>
          <AlbumProvider>
            <ReviewProvider>
              <SubscriberProvider>{children}</SubscriberProvider>
              <ToastContainer />
            </ReviewProvider>
          </AlbumProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
