// 'use server'
import { Inter } from "next/font/google";
import "./globals.css";
import SessionWrapper from "./Componants/SessionWrapper";
import { AlbumProvider } from "./context/AlbumContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Sketch Artist - Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <SessionWrapper>
        <AlbumProvider>
          <body className={inter.className}>{children}</body>
        </AlbumProvider>
      </SessionWrapper>
    </html>
  );
}
