// 'use server'
import { Inter } from "next/font/google";
import "./globals.css";
import SessionWrapper from "./Componants/SessionWrapper";
import { AlbumProvider } from "./context/AlbumContext";
import ReviewProvider from "./context/ReviewContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Raj Artist",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <SessionWrapper>
        <AlbumProvider>
          <ReviewProvider>
            <body className={inter.className}>{children}</body>
          </ReviewProvider>
        </AlbumProvider>
      </SessionWrapper>
    </html>
  );
}
